apiVersion: v1
kind: Service
metadata:
  name: prometheus-stack-kube-prom-prometheus-nodeport
  namespace: monitoring
  labels:
    app: kube-prometheus-stack-prometheus
    app.kubernetes.io/instance: prometheus-stack
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: kube-prometheus-stack
    app.kubernetes.io/version: 66.3.1
    release: prometheus-stack
    self-monitor: "true"
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
    operator.prometheus.io/name: prometheus-stack-kube-prom-prometheus
  ports:
    - name: http-web
      port: 9090           # External port for accessing Prometheus
      protocol: TCP
      targetPort: 9090     # Target port inside the container
      nodePort: 30090      # Optional: Specify a custom NodePort
