apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: default
data:
  nginx.conf: |
    events {}
    http {
      server {
        listen 80;
        location / {
          return 200 'Hello from Nginx!';
        }

        # Expose metrics in a stub_status endpoint
        location /nginx_status {
          stub_status;
          # Allow localhost to access this endpoint
          # If running exporter as a sidecar in the same pod, this is sufficient
          allow all;
        }
      }
    }

