apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: go-http-server
  namespace: default
spec:
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 50
          type: Utilization
      type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-http-server
